spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ToyBoardTest1 # 메모리 데이터베이스 사용
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create # 데이터베이스 스키마 자동 업데이트
    show-sql: true # JPA SQL 로그 출력
    database-platform: org.hibernate.dialect.H2Dialect # H2 데이터베이스 방언 지정

server:
  port: 8080 # 서버 포트 설정

logging:
  level:
    org.springframework.web: DEBUG # 스프링 웹 로그 레벨 설정
